Fix EthereumPoW, adopt https://github.com/fuichain/mainnet-fork
ethereumpow/go-ethereum pull request #21
Opened 2022-09-10 08:29 UTC by fUpIndividual

fixes #17 #16 #13 #12
@roberto-bayardo @LefterisJP please feel free to review

2022-09-10 12:26 UTC, minernakamoto requested changes
This PR seems like more than a combination with unnecessary changes, see PR #20 for the necessary changes.

2022-09-15 14:44 UTC, nrjshka approved these changes

2022-09-16 13:41 UTC, pasha121 approved these changes

2022-09-16 14:12 UTC, krivichigor approved these changes

2022-10-16 02:45 UTC, Louisthomas422 approved these changes

2024-04-10 08:23 UTC, closed without merging