reset new chainId after EthPowBlock
ethereumpow/go-ethereum pull request #9
Opened 2022-08-24 09:27 UTC by CrisChain

reset new chainId after EthPowBlock

2022-08-25 14:02 UTC, dddddddddddddddddde approved these changes

2022-08-25 14:28 UTC, dddddddddddddddddde approved these changes

2022-08-25 15:05 UTC, mintnothing requested changes
no

2022-08-26 13:12 UTC, dddddddddddddddddbdde requested changes
chain id could better be changed more earlier

2022-09-02 05:52 UTC, closed without merging